name: build
on: push
jobs:
  build:
    name: my job
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node: [10, 12, 14]
        exclude:
          - os: macos-latest
            node: 10
    steps:
      - name: my first step
        env:
          MY_VAR: Hi there! my name is
          FIRST_NAME: Mohannad
          LAST_NAME: Emhemed
        run: echo $MY_VAR $FIRST_NAME $LAST_NAME
